export enum GekobereichCodeEnum {
    GESCHAEFTSBEREICH_ANBIETER = 'A',
    GESCHAEFTSBEREICH_GEKO = 'K',
    GESCHAEFTSBEREICH_STES = 'S',
    GESCHAEFTSBEREICH_ARBEITGEBER = 'G',
    GESCHAEFTSBEREICH_FACHBERATUNG = 'F',
    GESCHAEFTSBEREICH_AMM = 'M'
}
