export enum HttpFormStateEnum {
    SAVE_SUCCESS = 'SAVE_SUCCESS',
    GET_SUCCESS = 'GET_SUCCESS',
    SAVE_FAIL = 'SAVE_FAIL',
    SAVE_NO_RESPONCE = 'SAVE_NO_RESPONCE',
    GET_FAIL = 'GET_FAIL',
    GET_NO_RESPONCE = 'GET_NO_RESPONCE'
}
