export enum AmmButtonsTypeEnum {
    FKT_BEARBEITBAR = 1,
    FKT_LOESCHBAR = 2,
    FKT_ZURUECKNEHMBAR = 3,
    FKT_ERSETZBAR = 4,
    FKT_DOKS_ERSTELLBAR = 5,
    FKT_FREIGEBBAR = 6,
    FKT_UEBERARBEITBAR = 7,
    FKT_FOLGEGESUCH = 8,
    FKT_BUCHBAR = 9,
    FKT_ERSTELLBAR = 10,
    FKT_SPEICHERBAR = 11,
    FKT_VW_ERSTELLBAR = 12,
    FKT_DOKUMENTMANAGER = 13,
    FKT_DATEN_UEBERNEHMBAR = 14
}
