export enum AmmGeldgeberCode {
    ARBEITSLOSENVERSICHERUNG = '1',
    KANTONALEARBEITSLOSENHILFE = '2',
    KANTONALEFUERSORGE = '3',
    BUNDESAMTFUERMIGRATION = '4',
    INVALIDENVERSICHERUNG = '5',
    SCHWEIZERISCHEUNFALLVERSICHERUNGSANSTALT = '6'
}
