export enum AufenthaltsstatusCodeEnum {
    B_EUEFTA_AUFENTHALTSBEWILLIGUNG = '10',
    B_AUFENTHALTSBEWILLIGUNG = '11',
    B_AUFENTHALTSBEWILLIGUNG_FLUECHTLINGE = '12',
    C_EUEFTA_NIEDERLASSUNGSBEWILLIGUNG = '20',
    C_NIEDERLASSUNGSBEWILLIGUNG = '21',
    CI_EUEFTA_AUFENTHALTSBEWILL_MIT_ERWERBSTAETIGK = '25',
    CI_AUFENTHALTSBEWILL_MIT_ERWERBSTAETIGK = '26',
    F_VORLAEFIG_AUFGENOMMENE_AUSLAENDER = '40',
    F_VORLAEFIG_AUFGENOMMENE_FLUECHTLINGE = '41',
    G_EUEFTA_GRENZGAENGERBEWILLIGUNG = '50',
    G_GRENZGAENGERBEWILLIGUNG = '51',
    K_NOCH_NICHT_ABGEKLAERT = '99',
    L_EUEFTA_KURZAUFENTHALTSBEWILLIGUNG = '70',
    L_KURZAUFENTHALTSBEWILLIGUNG = '71',
    N_AUSWEIS_FUER_ASYLSUCHENDE = '80',
    S_SCHUTZBEDUERFTIGE = '90',
    EUEFTA_STELLENSUCHENDE = '98'
}
