export enum GesuchstypAZCodeEnum {
    HAUPTGESUCH = '0',
    FOLGEGESUCH_1 = '1',
    FOLGEGESUCH_2 = '2',
    FOLGEGESUCH_3 = '3',
    FOLGEGESUCH_4 = '4',
    FOLGEGESUCH_5 = '5',
    FOLGEGESUCH_6 = '6',
    FOLGEGESUCH_7 = '7',
    FOLGEGESUCH_8 = '8',
    FOLGEGESUCH_9 = '9',
    FOLGEGESUCH_10 = '10',
    FOLGEGESUCH_11 = '11',
    FOLGEGESUCH_12 = '12',
    FOLGEGESUCH_13 = '13',
    FOLGEGESUCH_14 = '14',
    FOLGEGESUCH_15 = '15',
    FOLGEGESUCH_16 = '16'
}
