export enum KurzarbeitEntscheidEnum {
    KAE_ENTSCHEID_KEIN_EINSPRUCH = '0',
    KAE_ENTSCHEID_TEILWEISE_EINSPRUCH = '1',
    KAE_ENTSCHEID_EINSPRUCH = '2',
    KAE_ENTSCHEID_RUECKZUG_ARBEITGEBER = '3',
    KAE_ENTSCHEID_NICHTEINTRETEN = '4',
    KAE_ENTSCHEID_UNGUELTIG = '5'
}
