export enum MobilitaetCodeEnum {
    MOBILITAET_NICHT_MOBIL = '1',
    MOBILITAET_TAGESPENDLER = '2',
    MOBILITAET_IN_TEILEN_DER_SCHWEIZ = '3',
    MOBILITAET_IN_DER_GANZEN_SCHWEIZ = '4',
    MOBILITAET_AUCH_INS_AUSLAND = '9'
}
