export enum SchnellzuweisungCodeEnum {
    PENDENT = '1',
    ERLEDIGT = '2',
    FREIGABEBEREIT = '3',
    VORGEMERKT = '4',
    ZUGESTELLT = '5',
    VERMITTLUNGSERGEBNIS_NICHT_GEEIGNET = '5',
    VERMITTLUNGSERGEBNIS_STELLE_ERHALTEN = '1',
    VERMITTLUNGSERGEBNIS_NICHT_ERHALTEN = '2'
}
