export enum StesAnmeldungsartCodeEnum {
    STES_ANMELDUNGSART_ERSTANMELDUNG = '1',
    STES_ANMELDUNGSART_WIEDERANMELDUNG_KLEINER_6MT = '2',
    STES_ANMELDUNGSART_WIEDERANMELDUNG_GROESSER_6MT = '3',
    STES_ANMELDUNGSART_RAVWECHSEL = '4'
}
