export enum SweStatusEnum {
    SWE_STATUS_PENDENT = '0',
    SWE_STATUS_MAHNUNG = '1',
    SWE_STATUS_FREIGABEBEREIT = '2',
    SWE_STATUS_FREIGEGEBEN = '3',
    SWE_STATUS_INUEBERARBEITUNG = '4',
    SWE_STATUS_ERSETZT = '9'
}
