export enum VoranmeldungErfassenConstant {
    CHANNEL = 'voranmeldung-erfassen',
    LOESCHENABBRECHEN = 'common.button.loeschenabbrechen',
    JA_LOESCHEN = 'common.button.jaLoeschen',
    JA_ERSETZEN = 'common.button.jaErsetzen',
    NICHT_ERSETZEN = 'common.button.nichtErsetzen',
    SIDE_NAV_ITEM_PATH_ERFASSEN = './kurzarbeit/voranmeldungen/erfassen',
    SIDE_NAV_ITEM_PATH_BEARBEITEN = './kurzarbeit/voranmeldungen/bearbeiten',
    ERSTELLEN_TITLE = 'kaeswe.label.voranmeldungerfassen',
    BEARBEITEN_TITLE = 'kaeswe.label.voranmeldung',
    DATENWIRKLICHLOESCHEN = 'common.label.datenWirklichLoeschen',
    VORANMELDUNGERSETZENBESTAETIGEN = 'kaeswe.message.voranmeldungersetzenbestaetigen',
    UNTERNEHMENNICHTAKTIV = 'kaeswe.error.unternehmennichtaktiv',
    PFLICHTFELDER = 'stes.error.bearbeiten.pflichtfelder',
    VORANMELDUNGERSETZT = 'kaeswe.message.voranmeldungersetzt',
    DATEN_KOPIERT = 'kaeswe.feedback.voranmeldungkaekopiert',
    VORANMELDUNG_KAE_ID = 'voranmeldungKaeId',
    KATEGORIE_KURZARBEIT = '1',
    ENTSCHEID_KEIN_EINSPRUCH = '0',
    ENTSCHEID_TEILWEISE_EINSPRUCH = '1'
}
