import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { BewirtschaftungRoutingModule } from './bewirtschaftung-routing.module';
import { SharedModule } from '@app/shared/shared.module';
import { CdkTableModule } from '@angular/cdk/table';
import * as components from './components/index';
import * as pages from './pages/index';
import { GeschlechtPipe } from '@app/shared';
import { AmmBewirtschaftungNavigationHelper } from './services/amm-bewirtschaftung-navigation-helper.service';
import { AmmTeilnehmerlisteHelperService } from './services/amm-teilnehmerliste-helper.service';
import { AmmPlanwertStorageService } from './services/bew-planwerte-storage.service';

@NgModule({
    declarations: [
        components.BewBeschreibungFormComponent,
        components.BewDurchfuehrungsortFormComponent,
        components.BewDfeUebersichtTableComponent,
        components.BewMassnahmeGrunddatenFormComponent,
        components.BewMassnahmeSuchenFormComponent,
        components.BewMassnahmeSuchenTableComponent,
        components.BewMassnahmenUebersichtTableComponent,
        components.BewProduktGrunddatenFormComponent,
        components.BewProduktSuchenFormComponent,
        components.BewProduktSuchenTableComponent,
        components.BewDfeSuchenFormComponent,
        components.BewDfeSuchenTableComponent,
        components.BewMassnahmeKostenFormComponent,
        components.BewMassnahmeReserviertePlaetzeTableComponent,
        components.BewPlanwerteUebersichtTableComponent,
        components.BewPlanwertFormComponent,
        components.BewKursGrunddatenFormComponent,
        components.BewStandortGrunddatenFormComponent,
        components.BewMassnahmeTeilnehmerlisteFormComponent,
        components.BewBeschaeftigungseinheitenTableComponent,
        components.BewMassnahmeTeilnehmerlisteTableComponent,
        components.BewMassnahmeTeilnehmerplaetzeTableComponent,
        components.BewBeschaeftigungseinheitGrunddatenFormComponent,
        components.BewPlanwertControllingwerteFormComponent,
        components.BewVertragswerteUebersichtTableComponent,
        components.BewVertragswertZuordnenModalComponent,
        components.BewVertragswertZuordnenTableComponent,
        pages.BewDfeSuchenComponent,
        pages.BewProduktHomeComponent,
        pages.BewMassnahmeHomeComponent,
        pages.BewKursHomeComponent,
        pages.BewStandortHomeComponent,
        pages.BewProduktGrunddatenBearbeitenComponent,
        pages.BewProduktBeschreibungBearbeitenComponent,
        pages.BewProduktSuchenComponent,
        pages.BewProduktErfassenWizardComponent,
        pages.BewProduktGrunddatenErfassenComponent,
        pages.BewProduktBeschreibungErfassenComponent,
        pages.BewMassnahmeSuchenComponent,
        pages.BewMassnahmenUebersichtComponent,
        pages.BewDfeUebersichtComponent,
        pages.BewMassnahmeErfassenWizardComponent,
        pages.BewMassnahmeBeschreibungErfassenComponent,
        pages.BewMassnahmeDurchfuehrungsortErfassenComponent,
        pages.BewMassnahmeGrunddatenErfassenComponent,
        pages.BewMassnahmeKostenComponent,
        pages.BewMassnahmeGrunddatenBearbeitenComponent,
        pages.BewMassnahmeBeschreibungBearbeitenComponent,
        pages.BewMassnahmeReserviertePlaetzeComponent,
        pages.BewStandortTeilnehmerlisteComponent,
        pages.BewKursGrunddatenErfassenComponent,
        pages.BewKursBeschreibungErfassenComponent,
        pages.BewKursDurchfuehrungsortErfassenComponent,
        pages.BewKursErfassenWizardComponent,
        pages.BewStandortGrunddatenErfassenComponent,
        pages.BewStandortBeschreibungErfassenComponent,
        pages.BewStandortDurchfortErfassenComponent,
        pages.BewStandortErfassenWizardComponent,
        pages.BewMassnahmeTeilnehmerlisteComponent,
        pages.BewDfeTeilnehmerlisteComponent,
        pages.BewPraktikumsstellenUebersichtComponent,
        pages.BewKursGrunddatenBearbeitenComponent,
        pages.BewArbeitsplatzkategorienComponent,
        pages.BewProduktPlanwerteUebersichtComponent,
        pages.BewMassnahmePlanwerteUebersichtComponent,
        pages.BewKursPlanwerteUebersichtComponent,
        pages.BewStandortPlanwerteUebersichtComponent,
        pages.BewStandortGrunddatenBearbeitenComponent,
        pages.BewProduktPlanwertErfassenComponent,
        pages.BewKursPlanwertErfassenComponent,
        pages.BewStandortPlanwertErfassenComponent,
        pages.BewMassnahmePlanwertErfassenComponent,
        pages.BewStandortTeilnehmerplaetzeComponent,
        pages.BewBeschaeftigungseinheitErfassenWizardComponent,
        pages.BewBeschaeftigungseinheitGrunddatenErfassenComponent,
        pages.BewBeschaeftigungseinheitDurchfortErfassenComponent,
        pages.BewBeschaeftigungseinheitBeschreibungErfassenComponent,
        pages.BewBeschaeftigungseinheitTeilnehmerlisteComponent,
        pages.BewKursWartelisteComponent,
        pages.BewBeschaeftigungseinheitHomeComponent,
        pages.BewKursBeschreibungBearbeitenComponent,
        pages.BewStandortBeschreibungBearbeitenComponent,
        pages.BewBeeGrunddatenBearbeitenComponent,
        pages.BewBeeBeschreibungBearbeitenComponent,
        pages.BewBeschaeftigungseinheitTeilnehmerplaetzeComponent,
        pages.BewKursDurchfuehrungsortBearbeitenComponent,
        pages.BewStandortPlanwertBearbeitenComponent,
        pages.BewProduktPlanwertBearbeitenComponent,
        pages.BewKursPlanwertBearbeitenComponent,
        pages.BewMassnahmePlanwertBearbeitenComponent,
        pages.BewMassnahmeDurchfuehrungsortBearbeitenComponent,
        pages.BewStandortDurchfuehrungsortBearbeitenComponent,
        pages.BewBeeDurchfuehrungsortBearbeitenComponent,
        pages.BewProduktPlanwertControllingwerteComponent,
        pages.BewKursPlanwertControllingwerteComponent,
        pages.BewStandortPlanwertControllingwerteComponent,
        pages.BewMassnahmePlanwertControllingwerteComponent,
        pages.BewMassnahmeVertragswerteComponent,
        pages.BewKursVertragswerteComponent,
        pages.BewStandortVertragswerteComponent,
        pages.BewKursPlanwertHomeComponent,
        pages.BewStandortPlanwertHomeComponent,
        pages.BewMassnahmePlanwertHomeComponent,
        pages.BewProduktPlanwertHomeComponent
    ],
    imports: [CommonModule, BewirtschaftungRoutingModule, SharedModule, CdkTableModule],
    providers: [GeschlechtPipe, AmmBewirtschaftungNavigationHelper, AmmTeilnehmerlisteHelperService, AmmPlanwertStorageService]
})
export class BewirtschaftungModule {}
